# Generated by Django 3.2.7 on 2021-09-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='status_like',
            field=models.TextField(default=False, verbose_name='Нравится'),
        ),
    ]
