# Generated by Django 3.2.7 on 2021-09-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_bot', '0003_alter_stuff_status_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='status_like',
            field=models.JSONField(default=[False], verbose_name='Нравится'),
        ),
    ]
