# Generated by Django 3.2.7 on 2021-09-26 18:58

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_bot', '0007_alter_stuff_status_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='status_like_users',
            field=jsonfield.fields.JSONField(default=False),
        ),
    ]
