# Generated by Django 3.2.7 on 2021-09-27 08:40

from django.db import migrations


def copy_name_to_username(apps, schema_editor):
    Profile = apps.get_model('stuff_bot', 'Profile')
    for profile in Profile.objects.all():
        profile.tg_username = profile.name
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_bot', '0009_auto_20210927_0839'),
    ]

    operations = [
        migrations.RunPython(copy_name_to_username),
    ]
